In [1]:
%matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
import seaborn as sns
sns.set_style("whitegrid")
sns.set_context("poster")
import re
import csv
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import LabelEncoder

/Users/hechengwang/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

In [2]:
train = pd.read_csv("train.csv", header = 0)
test = pd.read_csv("test.csv", header = 0)

In [18]:
def clean_data(df):
    
    #gender and embarked binarization
    df = pd.concat([df, pd.get_dummies(df['Sex'])], axis = 1)
    df = pd.concat([df, pd.get_dummies(df['Embarked'].fillna('S'), prefix= 'Embarked')], axis = 1)
      
    #create new feature called famsize
    df['FamilySize'] = df['SibSp'] + df['Parch'] + 1.0
    df['Family']=df['SibSp']*df['Parch']
    #fare fix
    df.loc[ (df.Fare.isnull())&(df.Pclass==1),'Fare'] =np.median(df[df['Pclass'] == 1]['Fare'].dropna())
    df.loc[ (df.Fare.isnull())&(df.Pclass==2),'Fare'] =np.median( df[df['Pclass'] == 2]['Fare'].dropna())
    df.loc[ (df.Fare.isnull())&(df.Pclass==3),'Fare'] = np.median(df[df['Pclass'] == 3]['Fare'].dropna())
    df['Fare_Per_Person'] = df['Fare'] / df['FamilySize']

    #title
    title_transforms = {'Dona.': 'Mrs.',
                        'Countess.': 'Mrs.',
                        'Jonkheer.': 'Mr.',
                        'Capt.': 'Mr.',
                        'Don.': 'Mr.',
                        'Lady.': 'Mrs.',
                        'Major.': 'Mr.',
                        'Mlle.': 'Mrs.',
                        'Mme.': 'Mrs.',
                        'Sir.': 'Master.'}
    
    df['Title'] = df['Name'].str.extract("([\w]+\.)")
    df['Title'] = df.replace({'Title': title_transforms})['Title']
    def replace_titles(x):
        title=x['Title']
        if title in ['Mr.','Don.', 'Major.', 'Capt.', 'Jonkheer.', 'Rev.', 'Col.']:
            return 'Mr.'
        elif title in ['Master.']:
            return 'Master.'
        elif title in ['Countess.', 'Mme.','Mrs.']:
            return 'Mrs.'
        elif title in ['Mlle.', 'Ms.','Miss.']:
            return 'Miss.'
        elif title =='Dr.':
            if x['Sex']=='Male':
                return 'Mr.'
            else:
                return 'Mrs.'
        elif title =='':
            if x['Sex']=='Male':
                return 'Master.'
            else:
                return 'Miss.'
        else:
            return title

    df['Title']=df.apply(replace_titles, axis=1)
    df = pd.concat([df, pd.get_dummies(df['Title'], prefix = 'Title')], axis = 1)
    
    #age fix
    df['AgeFill'] = df['Age'] \
        .groupby([df['Sex'], df['Title']]) \
        .apply(lambda x: x.fillna(x.mean()))
    
    df['AgeCat']=df['AgeFill']
    df.loc[ (df.AgeFill<=10) ,'AgeCat'] = 'child'
    df.loc[ (df.AgeFill>60),'AgeCat'] = 'aged'
    df.loc[ (df.AgeFill>10) & (df.AgeFill <=30) ,'AgeCat'] = 'adult'
    df.loc[ (df.AgeFill>30) & (df.AgeFill <=60) ,'AgeCat'] = 'senior'
    df = pd.concat([df, pd.get_dummies(df['AgeCat'], prefix = 5)], axis = 1)
    
    #cabin fix
    df['Cabin_Category'] = df['Cabin'].str.extract("(\w)").fillna("")
    df['Cabin_Category'] = np.where(df['Cabin_Category'] == "", 0, 1)
    
    
    #added features
    df['AgeClass']=df['AgeFill']*df['Pclass']
    df['ClassFare']=df['Pclass']*df['Fare_Per_Person']
    df['HighLow']=df['Pclass']
    df.loc[ (df.Fare_Per_Person<8) ,'HighLow'] = 0
    df.loc[ (df.Fare_Per_Person>=8) ,'HighLow'] = 1
    
    le = LabelEncoder()
    le.fit(df['Ticket'])
    df['Ticket'] = le.transform(df['Ticket'])
    
    df = df.drop(['PassengerId', 'Age', 'AgeCat', 'Name', 'Sex', 'Embarked', 'Cabin', 'Ticket', 'Title'], axis = 1)
    return df

In [19]:
x = clean_data(train).drop('Survived', axis = 1)
y = train['Survived']
test_new = clean_data(test)

In [20]:
x

     Pclass  SibSp  Parch      Fare  female  male  Embarked_C  Embarked_Q  Embarked_S  FamilySize  Family  Fare_Per_Person  Title_Master.  Title_Miss.  Title_Mr.  Title_Mrs.    AgeFill  5_adult  5_aged  5_child  5_senior  Cabin_Category    AgeClass  ClassFare  HighLow
0         3      1      0    7.2500       0     1           0           0           1           2       0         3.625000              0            0          1           0  22.000000        1       0        0         0               0   66.000000  10.875000        0
1         1      1      0   71.2833       1     0           1           0           0           2       0        35.641650              0            0          0           1  38.000000        0       0        0         1               1   38.000000  35.641650        1
2         3      0      0    7.9250       1     0           0           0           1           1       0         7.925000              0            1          0           0  26.000000        1       0        0         0               0   78.000000  23.775000        0
3         1      1      0   53.1000       1     0           0           0           1           2       0        26.550000              0            0          0           1  35.000000        0       0        0         1               1   35.000000  26.550000        1
4         3      0      0    8.0500       0     1           0           0           1           1       0         8.050000              0            0          1           0  35.000000        0       0        0         1               0  105.000000  24.150000        1
5         3      0      0    8.4583       0     1           0           1           0           1       0         8.458300              0            0          1           0  32.852798        0       0        0         1               0   98.558394  25.374900        1
6         1      0      0   51.8625       0     1           0           0           1           1       0        51.862500              0            0          1           0  54.000000        0       0        0         1               1   54.000000  51.862500        1
7         3      3      1   21.0750       0     1           0           0           1           5       3         4.215000              1            0          0           0   2.000000        0       0        1         0               0    6.000000  12.645000        0
8         3      0      2   11.1333       1     0           0           0           1           3       0         3.711100              0            0          0           1  27.000000        1       0        0         0               0   81.000000  11.133300        0
9         2      1      0   30.0708       1     0           1           0           0           2       0        15.035400              0            0          0           1  14.000000        1       0        0         0               0   28.000000  30.070800        1
10        3      1      1   16.7000       1     0           0           0           1           3       1         5.566667              0            1          0           0   4.000000        0       0        1         0               1   12.000000  16.700000        0
11        1      0      0   26.5500       1     0           0           0           1           1       0        26.550000              0            1          0           0  58.000000        0       0        0         1               1   58.000000  26.550000        1
12        3      0      0    8.0500       0     1           0           0           1           1       0         8.050000              0            0          1           0  20.000000        1       0        0         0               0   60.000000  24.150000        1
13        3      1      5   31.2750       0     1           0           0           1           7       5         4.467857              0            0          1           0  39.000000        0       0        0         1               0  117.000000  13.403571        0
14        3      0      0    7.8542       1     0           0           0           1           1       0         7.854200              0            1          0           0  14.000000        1       0        0         0               0   42.000000  23.562600        0
15        2      0      0   16.0000       1     0           0           0           1           1       0        16.000000              0            0          0           1  55.000000        0       0        0         1               0  110.000000  32.000000        1
16        3      4      1   29.1250       0     1           0           1           0           6       4         4.854167              1            0          0           0   2.000000        0       0        1         0               0    6.000000  14.562500        0
17        2      0      0   13.0000       0     1           0           0           1           1       0        13.000000              0            0          1           0  32.852798        0       0        0         1               0   65.705596  26.000000        1
18        3      1      0   18.0000       1     0           0           0           1           2       0         9.000000              0            0          0           1  31.000000        0       0        0         1               0   93.000000  27.000000        1
19        3      0      0    7.2250       1     0           1           0           0           1       0         7.225000              0            0          0           1  35.780702        0       0        0         1               0  107.342105  21.675000        0
20        2      0      0   26.0000       0     1           0           0           1           1       0        26.000000              0            0          1           0  35.000000        0       0        0         1               0   70.000000  52.000000        1
21        2      0      0   13.0000       0     1           0           0           1           1       0        13.000000              0            0          1           0  34.000000        0       0        0         1               1   68.000000  26.000000        1
22        3      0      0    8.0292       1     0           0           1           0           1       0         8.029200              0            1          0           0  15.000000        1       0        0         0               0   45.000000  24.087600        1
23        1      0      0   35.5000       0     1           0           0           1           1       0        35.500000              0            0          1           0  28.000000        1       0        0         0               1   28.000000  35.500000        1
24        3      3      1   21.0750       1     0           0           0           1           5       3         4.215000              0            1          0           0   8.000000        0       0        1         0               0   24.000000  12.645000        0
25        3      1      5   31.3875       1     0           0           0           1           7       5         4.483929              0            0          0           1  38.000000        0       0        0         1               0  114.000000  13.451786        0
26        3      0      0    7.2250       0     1           1           0           0           1       0         7.225000              0            0          1           0  32.852798        0       0        0         1               0   98.558394  21.675000        0
27        1      3      2  263.0000       0     1           0           0           1           6       6        43.833333              0            0          1           0  19.000000        1       0        0         0               1   19.000000  43.833333        1
28        3      0      0    7.8792       1     0           0           1           0           1       0         7.879200              0            1          0           0  21.816327        1       0        0         0               0   65.448980  23.637600        0
29        3      0      0    7.8958       0     1           0           0           1           1       0         7.895800              0            0          1           0  32.852798        0       0        0         1               0   98.558394  23.687400        0
..      ...    ...    ...       ...     ...   ...         ...         ...         ...         ...     ...              ...            ...          ...        ...         ...        ...      ...     ...      ...       ...             ...         ...        ...      ...
861       2      1      0   11.5000       0     1           0           0           1           2       0         5.750000              0            0          1           0  21.000000        1       0        0         0               0   42.000000  11.500000        0
862       1      0      0   25.9292       1     0           0           0           1           1       0        25.929200              0            0          0           1  48.000000        0       0        0         1               1   48.000000  25.929200        1
863       3      8      2   69.5500       1     0           0           0           1          11      16         6.322727              0            1          0           0  21.816327        1       0        0         0               0   65.448980  18.968182        0
864       2      0      0   13.0000       0     1           0           0           1           1       0        13.000000              0            0          1           0  24.000000        1       0        0         0               0   48.000000  26.000000        1
865       2      0      0   13.0000       1     0           0           0           1           1       0        13.000000              0            0          0           1  42.000000        0       0        0         1               0   84.000000  26.000000        1
866       2      1      0   13.8583       1     0           1           0           0           2       0         6.929150              0            1          0           0  27.000000        1       0        0         0               0   54.000000  13.858300        0
867       1      0      0   50.4958       0     1           0           0           1           1       0        50.495800              0            0          1           0  31.000000        0       0        0         1               1   31.000000  50.495800        1
868       3      0      0    9.5000       0     1           0           0           1           1       0         9.500000              0            0          1           0  32.852798        0       0        0         1               0   98.558394  28.500000        1
869       3      1      1   11.1333       0     1           0           0           1           3       1         3.711100              1            0          0           0   4.000000        0       0        1         0               0   12.000000  11.133300        0
870       3      0      0    7.8958       0     1           0           0           1           1       0         7.895800              0            0          1           0  26.000000        1       0        0         0               0   78.000000  23.687400        0
871       1      1      1   52.5542       1     0           0           0           1           3       1        17.518067              0            0          0           1  47.000000        0       0        0         1               1   47.000000  17.518067        1
872       1      0      0    5.0000       0     1           0           0           1           1       0         5.000000              0            0          1           0  33.000000        0       0        0         1               1   33.000000   5.000000        0
873       3      0      0    9.0000       0     1           0           0           1           1       0         9.000000              0            0          1           0  47.000000        0       0        0         1               0  141.000000  27.000000        1
874       2      1      0   24.0000       1     0           1           0           0           2       0        12.000000              0            0          0           1  28.000000        1       0        0         0               0   56.000000  24.000000        1
875       3      0      0    7.2250       1     0           1           0           0           1       0         7.225000              0            1          0           0  15.000000        1       0        0         0               0   45.000000  21.675000        0
876       3      0      0    9.8458       0     1           0           0           1           1       0         9.845800              0            0          1           0  20.000000        1       0        0         0               0   60.000000  29.537400        1
877       3      0      0    7.8958       0     1           0           0           1           1       0         7.895800              0            0          1           0  19.000000        1       0        0         0               0   57.000000  23.687400        0
878       3      0      0    7.8958       0     1           0           0           1           1       0         7.895800              0            0          1           0  32.852798        0       0        0         1               0   98.558394  23.687400        0
879       1      0      1   83.1583       1     0           1           0           0           2       0        41.579150              0            0          0           1  56.000000        0       0        0         1               1   56.000000  41.579150        1
880       2      0      1   26.0000       1     0           0           0           1           2       0        13.000000              0            0          0           1  25.000000        1       0        0         0               0   50.000000  26.000000        1
881       3      0      0    7.8958       0     1           0           0           1           1       0         7.895800              0            0          1           0  33.000000        0       0        0         1               0   99.000000  23.687400        0
882       3      0      0   10.5167       1     0           0           0           1           1       0        10.516700              0            1          0           0  22.000000        1       0        0         0               0   66.000000  31.550100        1
883       2      0      0   10.5000       0     1           0           0           1           1       0        10.500000              0            0          1           0  28.000000        1       0        0         0               0   56.000000  21.000000        1
884       3      0      0    7.0500       0     1           0           0           1           1       0         7.050000              0            0          1           0  25.000000        1       0        0         0               0   75.000000  21.150000        0
885       3      0      5   29.1250       1     0           0           1           0           6       0         4.854167              0            0          0           1  39.000000        0       0        0         1               0  117.000000  14.562500        0
886       2      0      0   13.0000       0     1           0           0           1           1       0        13.000000              0            0          1           0  27.000000        1       0        0         0               0   54.000000  26.000000        1
887       1      0      0   30.0000       1     0           0           0           1           1       0        30.000000              0            1          0           0  19.000000        1       0        0         0               1   19.000000  30.000000        1
888       3      1      2   23.4500       1     0           0           0           1           4       2         5.862500              0            1          0           0  21.816327        1       0        0         0               0   65.448980  17.587500        0
889       1      0      0   30.0000       0     1           1           0           0           1       0        30.000000              0            0          1           0  26.000000        1       0        0         0               1   26.000000  30.000000        1
890       3      0      0    7.7500       0     1           0           1           0           1       0         7.750000              0            0          1           0  32.000000        0       0        0         1               0   96.000000  23.250000        0

[891 rows x 25 columns]

In [22]:
test_new

     Pclass  SibSp  Parch      Fare  female  male  Embarked_C  Embarked_Q  Embarked_S  FamilySize  Family  Fare_Per_Person  Title_Master.  Title_Miss.  Title_Mr.  Title_Mrs.    AgeFill  5_adult  5_aged  5_child  5_senior  Cabin_Category    AgeClass   ClassFare  HighLow
0         3      0      0    7.8292       0     1           0           1           0           1       0         7.829200              0            0          1           0  34.500000        0       0        0         1               0  103.500000   23.487600        0
1         3      1      0    7.0000       1     0           0           0           1           2       0         3.500000              0            0          0           1  47.000000        0       0        0         1               0  141.000000   10.500000        0
2         2      0      0    9.6875       0     1           0           1           0           1       0         9.687500              0            0          1           0  62.000000        0       1        0         0               0  124.000000   19.375000        1
3         3      0      0    8.6625       0     1           0           0           1           1       0         8.662500              0            0          1           0  27.000000        1       0        0         0               0   81.000000   25.987500        1
4         3      1      1   12.2875       1     0           0           0           1           3       1         4.095833              0            0          0           1  22.000000        1       0        0         0               0   66.000000   12.287500        0
5         3      0      0    9.2250       0     1           0           0           1           1       0         9.225000              0            0          1           0  14.000000        1       0        0         0               0   42.000000   27.675000        1
6         3      0      0    7.6292       1     0           0           1           0           1       0         7.629200              0            1          0           0  30.000000        1       0        0         0               0   90.000000   22.887600        0
7         2      1      1   29.0000       0     1           0           0           1           3       1         9.666667              0            0          1           0  26.000000        1       0        0         0               0   52.000000   19.333333        1
8         3      0      0    7.2292       1     0           1           0           0           1       0         7.229200              0            0          0           1  18.000000        1       0        0         0               0   54.000000   21.687600        0
9         3      2      0   24.1500       0     1           0           0           1           3       0         8.050000              0            0          1           0  21.000000        1       0        0         0               0   63.000000   24.150000        1
10        3      0      0    7.8958       0     1           0           0           1           1       0         7.895800              0            0          1           0  32.229947        0       0        0         1               0   96.689840   23.687400        0
11        1      0      0   26.0000       0     1           0           0           1           1       0        26.000000              0            0          1           0  46.000000        0       0        0         1               0   46.000000   26.000000        1
12        1      1      0   82.2667       1     0           0           0           1           2       0        41.133350              0            0          0           1  23.000000        1       0        0         0               1   23.000000   41.133350        1
13        2      1      0   26.0000       0     1           0           0           1           2       0        13.000000              0            0          1           0  63.000000        0       1        0         0               0  126.000000   26.000000        1
14        1      1      0   61.1750       1     0           0           0           1           2       0        30.587500              0            0          0           1  47.000000        0       0        0         1               1   47.000000   30.587500        1
15        2      1      0   27.7208       1     0           1           0           0           2       0        13.860400              0            0          0           1  24.000000        1       0        0         0               0   48.000000   27.720800        1
16        2      0      0   12.3500       0     1           0           1           0           1       0        12.350000              0            0          1           0  35.000000        0       0        0         1               0   70.000000   24.700000        1
17        3      0      0    7.2250       0     1           1           0           0           1       0         7.225000              0            0          1           0  21.000000        1       0        0         0               0   63.000000   21.675000        0
18        3      1      0    7.9250       1     0           0           0           1           2       0         3.962500              0            1          0           0  27.000000        1       0        0         0               0   81.000000   11.887500        0
19        3      0      0    7.2250       1     0           1           0           0           1       0         7.225000              0            0          0           1  45.000000        0       0        0         1               0  135.000000   21.675000        0
20        1      1      0   59.4000       0     1           1           0           0           2       0        29.700000              0            0          1           0  55.000000        0       0        0         1               0   55.000000   29.700000        1
21        3      0      1    3.1708       0     1           0           0           1           2       0         1.585400              1            0          0           0   9.000000        0       0        1         0               0   27.000000    4.756200        0
22        1      0      0   31.6833       1     0           0           0           1           1       0        31.683300              0            0          0           1  38.904762        0       0        0         1               0   38.904762   31.683300        1
23        1      0      1   61.3792       0     1           1           0           0           2       0        30.689600              0            0          1           0  21.000000        1       0        0         0               0   21.000000   30.689600        1
24        1      1      3  262.3750       1     0           1           0           0           5       3        52.475000              0            0          0           1  48.000000        0       0        0         1               1   48.000000   52.475000        1
25        3      1      0   14.5000       0     1           0           0           1           2       0         7.250000              0            0          1           0  50.000000        0       0        0         1               0  150.000000   21.750000        0
26        1      0      1   61.9792       1     0           1           0           0           2       0        30.989600              0            1          0           0  22.000000        1       0        0         0               1   22.000000   30.989600        1
27        3      0      0    7.2250       0     1           1           0           0           1       0         7.225000              0            0          1           0  22.500000        1       0        0         0               0   67.500000   21.675000        0
28        1      0      0   30.5000       0     1           0           0           1           1       0        30.500000              0            0          1           0  41.000000        0       0        0         1               1   41.000000   30.500000        1
29        3      2      0   21.6792       0     1           1           0           0           3       0         7.226400              0            0          1           0  32.229947        0       0        0         1               0   96.689840   21.679200        0
..      ...    ...    ...       ...     ...   ...         ...         ...         ...         ...     ...              ...            ...          ...        ...         ...        ...      ...     ...      ...       ...             ...         ...         ...      ...
388       3      0      0    7.7500       0     1           0           1           0           1       0         7.750000              0            0          1           0  21.000000        1       0        0         0               0   63.000000   23.250000        0
389       3      3      1   21.0750       0     1           0           0           1           5       3         4.215000              1            0          0           0   6.000000        0       0        1         0               0   18.000000   12.645000        0
390       1      0      0   93.5000       0     1           0           0           1           1       0        93.500000              0            0          1           0  23.000000        1       0        0         0               1   23.000000   93.500000        1
391       1      0      1   39.4000       1     0           0           0           1           2       0        19.700000              0            0          0           1  51.000000        0       0        0         1               1   51.000000   19.700000        1
392       3      0      2   20.2500       0     1           0           0           1           3       0         6.750000              1            0          0           0  13.000000        1       0        0         0               0   39.000000   20.250000        0
393       2      0      0   10.5000       0     1           0           0           1           1       0        10.500000              0            0          1           0  47.000000        0       0        0         1               0   94.000000   21.000000        1
394       3      3      1   22.0250       0     1           0           0           1           5       3         4.405000              0            0          1           0  29.000000        1       0        0         0               0   87.000000   13.215000        0
395       1      1      0   60.0000       1     0           0           0           1           2       0        30.000000              0            0          0           1  18.000000        1       0        0         0               1   18.000000   30.000000        1
396       3      0      0    7.2500       0     1           0           1           0           1       0         7.250000              0            0          1           0  24.000000        1       0        0         0               0   72.000000   21.750000        0
397       1      1      1   79.2000       1     0           1           0           0           3       1        26.400000              0            0          0           1  48.000000        0       0        0         1               1   48.000000   26.400000        1
398       3      0      0    7.7750       0     1           0           0           1           1       0         7.775000              0            0          1           0  22.000000        1       0        0         0               0   66.000000   23.325000        0
399       3      0      0    7.7333       0     1           0           1           0           1       0         7.733300              0            0          1           0  31.000000        0       0        0         1               0   93.000000   23.199900        0
400       1      0      0  164.8667       1     0           0           0           1           1       0       164.866700              0            1          0           0  30.000000        1       0        0         0               1   30.000000  164.866700        1
401       2      1      0   21.0000       0     1           0           0           1           2       0        10.500000              0            0          1           0  38.000000        0       0        0         1               0   76.000000   21.000000        1
402       1      0      1   59.4000       1     0           1           0           0           2       0        29.700000              0            1          0           0  22.000000        1       0        0         0               0   22.000000   29.700000        1
403       1      0      0   47.1000       0     1           0           0           1           1       0        47.100000              0            0          1           0  17.000000        1       0        0         0               0   17.000000   47.100000        1
404       1      1      0   27.7208       0     1           1           0           0           2       0        13.860400              0            0          1           0  43.000000        0       0        0         1               1   43.000000   13.860400        1
405       2      0      0   13.8625       0     1           1           0           0           1       0        13.862500              0            0          1           0  20.000000        1       0        0         0               1   40.000000   27.725000        1
406       2      1      0   10.5000       0     1           0           0           1           2       0         5.250000              0            0          1           0  23.000000        1       0        0         0               0   46.000000   10.500000        0
407       1      1      1  211.5000       0     1           1           0           0           3       1        70.500000              0            0          1           0  50.000000        0       0        0         1               1   50.000000   70.500000        1
408       3      0      0    7.7208       1     0           0           1           0           1       0         7.720800              0            1          0           0  21.774844        1       0        0         0               0   65.324531   23.162400        0
409       3      1      1   13.7750       1     0           0           0           1           3       1         4.591667              0            1          0           0   3.000000        0       0        1         0               0    9.000000   13.775000        0
410       3      0      0    7.7500       1     0           0           1           0           1       0         7.750000              0            1          0           0  21.774844        1       0        0         0               0   65.324531   23.250000        0
411       1      1      0   90.0000       1     0           0           1           0           2       0        45.000000              0            0          0           1  37.000000        0       0        0         1               1   37.000000   45.000000        1
412       3      0      0    7.7750       1     0           0           0           1           1       0         7.775000              0            1          0           0  28.000000        1       0        0         0               0   84.000000   23.325000        0
413       3      0      0    8.0500       0     1           0           0           1           1       0         8.050000              0            0          1           0  32.229947        0       0        0         1               0   96.689840   24.150000        1
414       1      0      0  108.9000       1     0           1           0           0           1       0       108.900000              0            0          0           1  39.000000        0       0        0         1               1   39.000000  108.900000        1
415       3      0      0    7.2500       0     1           0           0           1           1       0         7.250000              0            0          1           0  38.500000        0       0        0         1               0  115.500000   21.750000        0
416       3      0      0    8.0500       0     1           0           0           1           1       0         8.050000              0            0          1           0  32.229947        0       0        0         1               0   96.689840   24.150000        1
417       3      1      1   22.3583       0     1           1           0           0           3       1         7.452767              1            0          0           0   7.406471        0       0        1         0               0   22.219412   22.358300        0

[418 rows x 25 columns]

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import cross_validation
from sklearn import preprocessing
from sklearn.cross_validation import KFold
from sklearn.metrics import accuracy_score
import scipy
import matplotlib as mpl
from sklearn.linear_model import LogisticRegression
from sklearn.grid_search import GridSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix

In [25]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(x, y, test_size = .33)

In [41]:
clfl2=XGBClassifier()
parameters = {'n_estimators': [100, 200, 300, 400, 500], 
              'max_depth': range(1, 6), 
              'reg_lambda': [1],
              'reg_alpha': [1]}
fitmodel = GridSearchCV(clfl2, param_grid=parameters, cv=10, scoring="accuracy")
fitmodel.fit(x_train, y_train)
fitmodel.best_estimator_, fitmodel.best_params_, fitmodel.best_score_, fitmodel.grid_scores_

(XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
        gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=1,
        min_child_weight=1, missing=None, n_estimators=200, nthread=-1,
        objective='binary:logistic', reg_alpha=1, reg_lambda=1,
        scale_pos_weight=1, seed=0, silent=True, subsample=1),
 {'max_depth': 1, 'n_estimators': 200, 'reg_alpha': 1, 'reg_lambda': 1},
 0.85402684563758391,
 [mean: 0.84564, std: 0.04062, params: {'n_estimators': 100, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 1},
  mean: 0.85403, std: 0.04195, params: {'n_estimators': 200, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 1},
  mean: 0.85067, std: 0.04078, params: {'n_estimators': 300, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 1},
  mean: 0.84732, std: 0.04136, params: {'n_estimators': 400, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 1},
  mean: 0.84732, std: 0.04680, params: {'n_estimators': 500, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 1},
  mean: 0.84564, std: 0.04612, params: {'n_estimators': 100, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 2},
  mean: 0.84564, std: 0.05471, params: {'n_estimators': 200, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 2},
  mean: 0.84228, std: 0.04798, params: {'n_estimators': 300, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 2},
  mean: 0.84732, std: 0.04351, params: {'n_estimators': 400, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 2},
  mean: 0.84564, std: 0.04445, params: {'n_estimators': 500, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 2},
  mean: 0.85067, std: 0.03858, params: {'n_estimators': 100, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 3},
  mean: 0.84899, std: 0.03846, params: {'n_estimators': 200, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 3},
  mean: 0.85067, std: 0.03975, params: {'n_estimators': 300, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 3},
  mean: 0.85067, std: 0.04044, params: {'n_estimators': 400, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 3},
  mean: 0.85067, std: 0.04044, params: {'n_estimators': 500, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 3},
  mean: 0.85403, std: 0.03620, params: {'n_estimators': 100, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 4},
  mean: 0.85403, std: 0.03751, params: {'n_estimators': 200, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 4},
  mean: 0.84899, std: 0.03501, params: {'n_estimators': 300, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 4},
  mean: 0.84899, std: 0.03501, params: {'n_estimators': 400, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 4},
  mean: 0.84899, std: 0.03501, params: {'n_estimators': 500, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 4},
  mean: 0.85067, std: 0.03548, params: {'n_estimators': 100, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 5},
  mean: 0.85403, std: 0.03196, params: {'n_estimators': 200, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 5},
  mean: 0.85067, std: 0.03275, params: {'n_estimators': 300, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 5},
  mean: 0.85067, std: 0.03275, params: {'n_estimators': 400, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 5},
  mean: 0.85067, std: 0.03275, params: {'n_estimators': 500, 'reg_lambda': 1, 'reg_alpha': 1, 'max_depth': 5}])

In [105]:
clfl2=RandomForestClassifier()
parameters = {'n_estimators': [100, 200, 300, 400, 500], 
              'max_depth': range(1, 6)}
fitmodel = GridSearchCV(clfl2, param_grid=parameters, cv=10, scoring="accuracy")
fitmodel.fit(x_train, y_train)
fitmodel.best_estimator_, fitmodel.best_params_, fitmodel.best_score_, fitmodel.grid_scores_

(RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
             max_depth=5, max_features='auto', max_leaf_nodes=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
             oob_score=False, random_state=None, verbose=0,
             warm_start=False),
 {'max_depth': 5, 'n_estimators': 200},
 0.83389261744966447,
 [mean: 0.78523, std: 0.06279, params: {'n_estimators': 100, 'max_depth': 1},
  mean: 0.78188, std: 0.06171, params: {'n_estimators': 200, 'max_depth': 1},
  mean: 0.78188, std: 0.06392, params: {'n_estimators': 300, 'max_depth': 1},
  mean: 0.77517, std: 0.06613, params: {'n_estimators': 400, 'max_depth': 1},
  mean: 0.78020, std: 0.06399, params: {'n_estimators': 500, 'max_depth': 1},
  mean: 0.80369, std: 0.06175, params: {'n_estimators': 100, 'max_depth': 2},
  mean: 0.79698, std: 0.05583, params: {'n_estimators': 200, 'max_depth': 2},
  mean: 0.80369, std: 0.05973, params: {'n_estimators': 300, 'max_depth': 2},
  mean: 0.80369, std: 0.06342, params: {'n_estimators': 400, 'max_depth': 2},
  mean: 0.80872, std: 0.06336, params: {'n_estimators': 500, 'max_depth': 2},
  mean: 0.81040, std: 0.06099, params: {'n_estimators': 100, 'max_depth': 3},
  mean: 0.81208, std: 0.06309, params: {'n_estimators': 200, 'max_depth': 3},
  mean: 0.81879, std: 0.05802, params: {'n_estimators': 300, 'max_depth': 3},
  mean: 0.81040, std: 0.06289, params: {'n_estimators': 400, 'max_depth': 3},
  mean: 0.81544, std: 0.06177, params: {'n_estimators': 500, 'max_depth': 3},
  mean: 0.81879, std: 0.05625, params: {'n_estimators': 100, 'max_depth': 4},
  mean: 0.81544, std: 0.05374, params: {'n_estimators': 200, 'max_depth': 4},
  mean: 0.81879, std: 0.05535, params: {'n_estimators': 300, 'max_depth': 4},
  mean: 0.81544, std: 0.05166, params: {'n_estimators': 400, 'max_depth': 4},
  mean: 0.81879, std: 0.05570, params: {'n_estimators': 500, 'max_depth': 4},
  mean: 0.83221, std: 0.05341, params: {'n_estimators': 100, 'max_depth': 5},
  mean: 0.83389, std: 0.05418, params: {'n_estimators': 200, 'max_depth': 5},
  mean: 0.83054, std: 0.04591, params: {'n_estimators': 300, 'max_depth': 5},
  mean: 0.83389, std: 0.05069, params: {'n_estimators': 400, 'max_depth': 5},
  mean: 0.83221, std: 0.05559, params: {'n_estimators': 500, 'max_depth': 5}])

In [28]:
for i in range(1, 11):
    clf = RandomForestClassifier(n_estimators = 500, max_depth = i)
    clf.fit(x_train, y_train)
    x_train_pred = clf.predict(x_train)
    x_test_pred = clf.predict(x_test)
    print "train-test accuracy: %s - %s %s" %(accuracy_score(x_train_pred, y_train), accuracy_score(x_test_pred, y_test), i)

train-test accuracy: 0.781879194631 - 0.796610169492 1
train-test accuracy: 0.791946308725 - 0.810169491525 2
train-test accuracy: 0.828859060403 - 0.840677966102 3
train-test accuracy: 0.838926174497 - 0.847457627119 4
train-test accuracy: 0.86744966443 - 0.840677966102 5
train-test accuracy: 0.889261744966 - 0.84406779661 6
train-test accuracy: 0.919463087248 - 0.847457627119 7
train-test accuracy: 0.93288590604 - 0.84406779661 8
train-test accuracy: 0.947986577181 - 0.84406779661 9
train-test accuracy: 0.956375838926 - 0.84406779661 10

In [101]:
for i in range(1, 20):
    clf = RandomForestClassifier(n_estimators = 500, max_depth = 7)
    clf.fit(x_train, y_train)
    x_train_pred = clf.predict(x_train)
    x_test_pred = clf.predict(x_test)
    print "train-test accuracy: %s - %s %s" %(accuracy_score(x_train_pred, y_train), accuracy_score(x_test_pred, y_test), i)

train-test accuracy: 0.887583892617 - 0.837288135593 1
train-test accuracy: 0.88255033557 - 0.837288135593 2
train-test accuracy: 0.880872483221 - 0.833898305085 3
train-test accuracy: 0.887583892617 - 0.830508474576 4
train-test accuracy: 0.885906040268 - 0.823728813559 5
train-test accuracy: 0.887583892617 - 0.830508474576 6
train-test accuracy: 0.879194630872 - 0.820338983051 7
train-test accuracy: 0.889261744966 - 0.827118644068 8
train-test accuracy: 0.892617449664 - 0.833898305085 9
train-test accuracy: 0.889261744966 - 0.823728813559 10
train-test accuracy: 0.879194630872 - 0.820338983051 11
train-test accuracy: 0.887583892617 - 0.830508474576 12
train-test accuracy: 0.879194630872 - 0.833898305085 13
train-test accuracy: 0.877516778523 - 0.830508474576 14
train-test accuracy: 0.894295302013 - 0.837288135593 15
train-test accuracy: 0.875838926174 - 0.823728813559 16
train-test accuracy: 0.874161073826 - 0.827118644068 17
train-test accuracy: 0.884228187919 - 0.833898305085 18
train-test accuracy: 0.885906040268 - 0.833898305085 19

In [100]:
test_new.describe()

           Pclass       SibSp       Parch      Ticket        Fare      female        male  Embarked_C  Embarked_Q  Embarked_S  FamilySize      Family  Fare_Per_Person  Title_Master.  Title_Miss.   Title_Mr.  Title_Mrs.     AgeFill     5_adult      5_aged     5_child    5_senior  Cabin_Category    AgeClass   ClassFare     HighLow
count  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000       418.000000     418.000000   418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000      418.000000  418.000000  418.000000  418.000000
mean     2.265550    0.447368    0.392344  180.944976   35.560845    0.363636    0.636364    0.244019    0.110048    0.645933    1.839713    0.444976        21.770888       0.050239     0.188995    0.583732    0.177033   30.222256    0.461722    0.026316    0.062201    0.449761        0.217703   63.568484   33.040328    0.557416
std      0.841838    0.896760    0.981429  107.533763   55.856972    0.481622    0.481622    0.430019    0.313324    0.478803    1.519072    1.668752        35.603507       0.218700     0.391974    0.493530    0.382154   13.021233    0.499130    0.160265    0.241810    0.498066        0.413179   29.849900   34.798837    0.497288
min      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000         0.000000       0.000000     0.000000    0.000000    0.000000    0.170000    0.000000    0.000000    0.000000    0.000000        0.000000    0.510000    0.000000    0.000000
25%      1.000000    0.000000    0.000000   85.250000    7.895800    0.000000    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000         7.634400       0.000000     0.000000    0.000000    0.000000   21.831133    0.000000    0.000000    0.000000    0.000000        0.000000   42.000000   21.675000    0.000000
50%      3.000000    0.000000    0.000000  181.000000   14.454200    0.000000    1.000000    0.000000    0.000000    1.000000    1.000000    0.000000         8.662500       0.000000     0.000000    1.000000    0.000000   30.000000    0.000000    0.000000    0.000000    0.000000        0.000000   61.500000   23.687400    1.000000
75%      3.000000    1.000000    0.000000  279.750000   31.471875    1.000000    1.000000    0.000000    0.000000    1.000000    2.000000    0.000000        25.982813       0.000000     0.000000    1.000000    0.000000   36.875000    1.000000    0.000000    0.000000    1.000000        0.000000   86.750000   27.720800    1.000000
max      3.000000    8.000000    9.000000  362.000000  512.329200    1.000000    1.000000    1.000000    1.000000    1.000000   11.000000   16.000000       262.375000       1.000000     1.000000    1.000000    1.000000   76.000000    1.000000    1.000000    1.000000    1.000000        1.000000  181.500000  262.375000    1.000000

In [29]:
clf = RandomForestClassifier(n_estimators = 500, max_depth = 7)
clf.fit(x, y)
output = clf.predict(test_new)
test_ids = test['PassengerId']

In [30]:
predictions_file = open("titanic_20160704.csv", "wb")
open_file_object = csv.writer(predictions_file)
open_file_object.writerow(["PassengerId","Survived"])
open_file_object.writerows(zip(test_ids, output))
predictions_file.close()

This will result in a prediction accuracy of 78.469%, which is better but not there yet :(

In [86]:
test_new.describe()

           Pclass       SibSp       Parch        Fare      female        male  Embarked_C  Embarked_Q  Embarked_S  FamilySize      Family  Fare_Per_Person  Title_Master.  Title_Miss.   Title_Mr.  Title_Mrs.     AgeFill  AgeCategory_adult  AgeCategory_aged  AgeCategory_child  AgeCategory_senior  Cabin_Category    AgeClass   ClassFare     HighLow
count  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000  418.000000       418.000000     418.000000   418.000000  418.000000  418.000000  418.000000         418.000000        418.000000         418.000000          418.000000      418.000000  418.000000  418.000000  418.000000
mean     2.265550    0.447368    0.392344   35.560845    0.363636    0.636364    0.244019    0.110048    0.645933    1.839713    0.444976        21.770888       0.050239     0.188995    0.583732    0.177033   30.222256           0.461722          0.026316           0.062201            0.449761        0.217703   63.568484   33.040328    0.557416
std      0.841838    0.896760    0.981429   55.856972    0.481622    0.481622    0.430019    0.313324    0.478803    1.519072    1.668752        35.603507       0.218700     0.391974    0.493530    0.382154   13.021233           0.499130          0.160265           0.241810            0.498066        0.413179   29.849900   34.798837    0.497288
min      1.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000         0.000000       0.000000     0.000000    0.000000    0.000000    0.170000           0.000000          0.000000           0.000000            0.000000        0.000000    0.510000    0.000000    0.000000
25%      1.000000    0.000000    0.000000    7.895800    0.000000    0.000000    0.000000    0.000000    0.000000    1.000000    0.000000         7.634400       0.000000     0.000000    0.000000    0.000000   21.831133           0.000000          0.000000           0.000000            0.000000        0.000000   42.000000   21.675000    0.000000
50%      3.000000    0.000000    0.000000   14.454200    0.000000    1.000000    0.000000    0.000000    1.000000    1.000000    0.000000         8.662500       0.000000     0.000000    1.000000    0.000000   30.000000           0.000000          0.000000           0.000000            0.000000        0.000000   61.500000   23.687400    1.000000
75%      3.000000    1.000000    0.000000   31.471875    1.000000    1.000000    0.000000    0.000000    1.000000    2.000000    0.000000        25.982813       0.000000     0.000000    1.000000    0.000000   36.875000           1.000000          0.000000           0.000000            1.000000        0.000000   86.750000   27.720800    1.000000
max      3.000000    8.000000    9.000000  512.329200    1.000000    1.000000    1.000000    1.000000    1.000000   11.000000   16.000000       262.375000       1.000000     1.000000    1.000000    1.000000   76.000000           1.000000          1.000000           1.000000            1.000000        1.000000  181.500000  262.375000    1.000000